### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by botany111** [LittleBigBug/acoworth#1]
Support QuickShop Reremake
https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/

**Comment by LittleBigBug** [comment]
Ok. I'll look into it a bit more. May be a little longer since QuickShop doesn't seem to have a very obvious API or maven support.

**Comment by LittleBigBug** [comment]
Added
83f41d4fb3c3730c60aa5a0fec6b9acd8fbfeec3
