### ISSUE TITLE
Unhandled Exception Error Bug Report

### ISSUE THREAD

**Issue by Stixil** [LittleBigBug/acoworth#18]
See stacktrace:
https://mcpaste.io/93b449b45a29540d

**Comment by LittleBigBug** [comment]
Thank you, When I find time I'll look into these issues 👍

**Comment by LittleBigBug** [comment]
Should be fixed in f1af607
This may have meant the database connection failed, so this "fix" will disable the plugin if a connection fails. (The null connection object was accessed when you typed the alias)
Please re-open this issue if this persists, I am not able to reliably recreate this.
