### ISSUE TITLE
Feature Request - Price Regulator for Admin Shops

### ISSUE THREAD

**Issue by Aeyori** [LittleBigBug/acoworth#4]
I would like to request a feature where your plugin is able to somewhat regulate the market!

For example: 
Base price of wood: $40

The price will fluctuate depending on how much is sold or how much is bought. 
My initial thought was that if a certain amount gets bought, then the price would be increased by an amount.

If an amount of wood is sold to the admin shop, the price would go down depending on how much it was sold for. 

Let me know your thoughts!! ^~^

**Comment by LittleBigBug** [comment]
If I sold wood to an admin shop the price on the admin shop would automatically decrease?
Is this globally or per player? I don't know if I fully understand

Sorry for the long delay in response

**Comment by Aeyori** [comment]
Hi, no problem for the late response!
Yes, so here's pretty much the idea.
These options would only apply to admin shops and not so much player shops. 

Buying:
If player buys X amount of item, price will go up because of less "supplies". (Even tho it's infinite). 
Selling price also goes up but at a significantly smaller rate or percentage.

Selling:
If player sells X amount of item, price will go down because of more "supplies". 
Selling price also goes down but at a significantly smaller rate or percentage.

**Comment by LittleBigBug** [comment]
Right right, ok. Sure.
I kinda like this idea, just sounds like a pain supporting every plugin.
When I get to this, I'll probably create a second branch and add quantumshop support and see how you like it. If it works well, cool, maybe later I will add support for chestshop3, quickshop, etc.

**Comment by Aeyori** [comment]
Yea, you're right it might be painful in that aspect and I do think it probably will be a definite time killer. I'll try contacting the plugin developer himself and see if he can implement this himself into the plugin that way it's more configurable to the plugin!

**Comment by LittleBigBug** [comment]
Unfortunately this is out of the scope for this project so I am going to close this issue. Maybe a solution to this is to add an API instead to easily access worth information.
this would be prone to abuse though
