### ISSUE TITLE
Request: BungeeCord support

### ISSUE THREAD

**Issue by Stixil** [LittleBigBug/acoworth#5]
We would love it on our server if the worth calculator could pick which servers from running on a proxy it would like to use to calculate the average for the group of servers. For example, a network with the following servers:
lobby
tutorial
smp
pvp
factions
survival_games

One could group smp and pvp together for a worth calculation, and factions and survival_games together for a separate worth calculation.

**Comment by LittleBigBug** [comment]
Hi,

I currently use SQLite to store worth data, I could provide MySQL support as a solution to this instead, would that suffice with this problem?

**Comment by Stixil** [comment]
Hello, I think that might work, I’m not exactly sure what would be best to have cross-server worth data.

**Comment by Stixil** [comment]
Actually yes, I think that would work quite nicely.

**Comment by LittleBigBug** [comment]
For sure. I will add this in the next version when I get to it.On Mar 30, 2020 11:08, Stixil <notifications@github.com> wrote:
Actually yes, I think that would work quite nicely.

**Comment by LittleBigBug** [comment]
Added MySQL support in 84c3bdb

**Comment by LittleBigBug** [comment]
Sorry for the wait, [here's the new build](https://www.spigotmc.org/resources/acoworth.74173/download?version=328861)
