### ISSUE TITLE
Add shop chest compatibility 

### ISSUE THREAD

**Issue by alextunbridge67** [LittleBigBug/acoworth#7]
Would really like to see the plugin be compatible with this plugin:
https://www.spigotmc.org/resources/shopchest.11431/

**Comment by LittleBigBug** [comment]
Will do, this should be in the next version.

**Comment by LittleBigBug** [comment]
[This is now in the new 1.6 version](https://github.com/LittleBigBug/acoworth/releases/download/untagged-7462a26724bbe35a11b1/AcoWorth-1.6.jar)
