### ISSUE TITLE
Table prefixes for MySQL storage

### ISSUE THREAD

**Issue by Stixil** [LittleBigBug/acoworth#9]
Hi, just a feature request to set table prefixes in the config when using MySQL. Thanks!

**Comment by LittleBigBug** [comment]
nearly forgot about that!! especially for shared mysql hosts.. I'm too spoiled with my own server. I'll do that asap but im pretty busy with other work.On May 16, 2020 13:23, Stixil <notifications@github.com> wrote:
Hi, just a feature request to set table prefixes in the config when using MySQL. Thanks!

**Comment by Stixil** [comment]
Thanks, no worries!

**Comment by LittleBigBug** [comment]
[See new release](https://github.com/LittleBigBug/acoworth/releases/download/untagged-7462a26724bbe35a11b1/AcoWorth-1.6.jar)
